"""
You are given an array of integers a. A new array b is generated by rearranging the elements of a in the following way:

b[0] is equal to a[0];
b[1] is equal to the last element of a;
b[2] is equal to a[1];
b[3] is equal to the second-last element of a;
b[4] is equal to a[2];
b[5] is equal to the third-last element of a;
and so on.
Here is how this process works:



Your task is to determine whether the new array b is sorted in strictly ascending order or not.
"""
def alternatingSort(a):
    i = -1
    start = 0
    end = len(a)-1
    prev = -1
    while start <= end:
        i += 1
        if i % 2 == 0:
            cur = start
            start += 1
        else:
            cur = end
            end -= 1
        if prev != -1 and a[prev] >= a[cur]:
            return False
        prev = cur
    return True    
